import React, { useState } from 'react';
import { ContentItem } from '../lib/types';
import { Twitter, Linkedin, Mail, Copy, Check, Edit3, Save, TrendingUp, Users, Eye, ArrowUpRight } from 'lucide-react';

interface ContentMatrixProps {
  contentItems: ContentItem[];
  onUpdateContentBody: (id: string, newBody: string) => void;
}

export default function ContentMatrix({ contentItems, onUpdateContentBody }: ContentMatrixProps) {
  const [filter, setFilter] = useState<'all' | 'x' | 'linkedin' | 'email'>('all');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editText, setEditText] = useState('');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const filteredItems = contentItems.filter((item) => {
    if (filter === 'all') return true;
    return item.channel === filter;
  });

  const handleCopy = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const startEditing = (item: ContentItem) => {
    setEditingId(item.id);
    setEditText(item.body);
  };

  const saveEditing = (id: string) => {
    onUpdateContentBody(id, editText);
    setEditingId(null);
  };

  const getChannelIcon = (channel: string) => {
    switch (channel) {
      case 'x':
        return <Twitter className="w-4 h-4 text-slate-100" />;
      case 'linkedin':
        return <Linkedin className="w-4 h-4 text-[#0A66C2]" />;
      case 'email':
        return <Mail className="w-4 h-4 text-accent-violet" />;
      default:
        return null;
    }
  };

  const getChannelLabel = (channel: string) => {
    switch (channel) {
      case 'x':
        return 'Twitter / X';
      case 'linkedin':
        return 'LinkedIn';
      case 'email':
        return 'Email Blast';
      default:
        return '';
    }
  };

  return (
    <div className="space-y-4">
      {/* Header and Filter Tabs */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 select-none">
        <h3 className="text-lg font-bold tracking-tight text-white flex items-center gap-2">
          <span>Generated Assets</span>
          <span className="text-xs bg-slate-800 text-slate-400 py-0.5 px-2 rounded-full border border-slate-700">
            {filteredItems.length} items
          </span>
        </h3>
        <div className="flex bg-space-950 p-1 rounded-xl border border-slate-800 self-stretch sm:self-auto">
          {(['all', 'x', 'linkedin', 'email'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`flex-1 sm:flex-none px-4 py-1.5 rounded-lg text-xs font-semibold uppercase tracking-wider transition-all duration-200 ${
                filter === tab
                  ? 'bg-space-800 text-white shadow-sm border border-slate-700/60'
                  : 'text-slate-500 hover:text-slate-300'
              }`}
            >
              {tab === 'all' ? 'All' : tab === 'x' ? 'X / Twitter' : tab === 'linkedin' ? 'LinkedIn' : 'Email'}
            </button>
          ))}
        </div>
      </div>

      {/* Grid List */}
      {filteredItems.length === 0 ? (
        <div className="glass-card rounded-2xl p-10 text-center text-slate-500 border border-dashed border-slate-800 italic">
          No marketing assets generated yet. Launch an orchestration run to generate content.
        </div>
      ) : (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
          {filteredItems.map((item) => (
            <div
              key={item.id}
              className="glass-card glass-card-hover rounded-2xl flex flex-col justify-between overflow-hidden relative group/card border border-slate-800/80"
            >
              {/* Card Header */}
              <div className="px-5 py-4 bg-space-950/40 border-b border-slate-850/80 flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className={`p-2 rounded-lg bg-slate-900 border border-slate-800`}>
                    {getChannelIcon(item.channel)}
                  </div>
                  <div>
                    <div className="text-xs font-bold text-white">{getChannelLabel(item.channel)}</div>
                    <div className="text-[10px] text-slate-500 font-medium">
                      {item.type.toUpperCase()} • Generated by AI
                    </div>
                  </div>
                </div>

                {/* Status Badge */}
                <div className="flex items-center gap-2">
                  <span
                    className={`text-[9px] uppercase tracking-widest font-extrabold px-2 py-0.5 rounded-full border ${
                      item.status === 'published'
                        ? 'bg-accent-emerald/10 text-accent-emerald border-accent-emerald/20'
                        : item.status === 'scheduled'
                        ? 'bg-accent-indigo/10 text-accent-indigo border-accent-indigo/20'
                        : 'bg-accent-violet/10 text-accent-violet border-accent-violet/20'
                    }`}
                  >
                    {item.status}
                  </span>
                </div>
              </div>

              {/* Card Content body */}
              <div className="p-5 flex-1 flex flex-col">
                {item.title && (
                  <h4 className="text-sm font-bold text-white mb-2 tracking-tight">
                    Subject: {item.title}
                  </h4>
                )}

                {editingId === item.id ? (
                  <textarea
                    value={editText}
                    onChange={(e) => setEditText(e.target.value)}
                    rows={6}
                    className="flex-1 w-full p-3 bg-space-950 border border-slate-800 rounded-xl text-sm font-mono text-slate-300 focus:outline-none focus:border-accent-indigo focus:ring-1 focus:ring-accent-indigo resize-none"
                  />
                ) : (
                  <p className="flex-1 text-sm text-slate-300 font-medium whitespace-pre-wrap leading-relaxed">
                    {item.body}
                  </p>
                )}
              </div>

              {/* Card Action footer */}
              <div className="px-5 py-3.5 bg-space-950/20 border-t border-slate-850/80 flex items-center justify-between">
                {/* Actions: Edit, Copy */}
                <div className="flex gap-2">
                  {editingId === item.id ? (
                    <button
                      onClick={() => saveEditing(item.id)}
                      className="flex items-center gap-1.5 py-1 px-3 rounded-lg bg-accent-emerald/10 border border-accent-emerald/20 hover:bg-accent-emerald/20 text-accent-emerald text-xs font-bold transition-all"
                    >
                      <Save className="w-3.5 h-3.5" />
                      <span>Save</span>
                    </button>
                  ) : (
                    <button
                      onClick={() => startEditing(item)}
                      className="flex items-center gap-1.5 py-1 px-3 rounded-lg bg-slate-900 border border-slate-800 hover:bg-slate-800 text-slate-400 hover:text-slate-200 text-xs font-bold transition-all"
                    >
                      <Edit3 className="w-3.5 h-3.5" />
                      <span>Edit</span>
                    </button>
                  )}
                  <button
                    onClick={() => handleCopy(item.id, item.body)}
                    className="flex items-center justify-center p-1.5 rounded-lg bg-slate-900 border border-slate-800 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-all"
                    title="Copy to clipboard"
                  >
                    {copiedId === item.id ? <Check className="w-3.5 h-3.5 text-accent-emerald" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>

                {/* Simulated Metrics for Published items */}
                {item.status === 'published' && item.metrics && (
                  <div className="flex items-center gap-4 text-[11px] text-slate-400 font-bold select-none">
                    <span className="flex items-center gap-1">
                      <Eye className="w-3.5 h-3.5 text-slate-500" />
                      <span>{(item.metrics.impressions || 0).toLocaleString()}</span>
                    </span>
                    <span className="flex items-center gap-1">
                      <ArrowUpRight className="w-3.5 h-3.5 text-accent-cyan" />
                      <span>{(item.metrics.clicks || 0).toLocaleString()} clicks</span>
                    </span>
                    <span className="flex items-center gap-1">
                      <Users className="w-3.5 h-3.5 text-accent-emerald" />
                      <span>{(item.metrics.signups || 0).toLocaleString()} signups</span>
                    </span>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
